### ISSUE TITLE
update container

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/app-pyafq-segment#3]
brainlife/pyafq:1.0 needs to be updated to incorporate the changes to the segment() function with the flag reset_tg_space

**Comment by brainlifeio** [comment]
We are installing it from pypi and the last release for pyAFQ was 0.4.1 on Sep 14th. 

> https://pypi.org/project/pyAFQ/

Is this the version we need?

**Comment by giulia-berto** [comment]
No, they will include it in version 0.5. Shall we resume the patched version then?

**Comment by brainlifeio** [comment]
@bacaron Do you need this patched ASAP, or can we wait for the 0.5 release?

**Comment by soichih** [comment]
Sorry above few comments are made by me. I forgot to switch account back to my personal one.

**Comment by giulia-berto** [comment]
I think it is better to have a functioning app in the meantime. I'm sorry @bacaron, I did update the v.1.0.0 with the latest change, but I think it is better to resume the segment-afq.py file to the previous commit.

**Comment by bacaron** [comment]
Not sure I'm following the issue or what needs to be done.

Do I just need to update the docker container?

**Comment by giulia-berto** [comment]
Sorry for the confusion, my mistake. I will now delete my commit in v1.0.0 branch, and everything should work as expected. We will need to update the container once the pyafq 0.5 version will be released in pypi (I thought it was already there).

**Comment by giulia-berto** [comment]
done, sorry again, I'll close this.
